# まとめ

In [48]:
text_parts = '前砂糖一郎19'
ngram(text_parts, 2)

[('前', '砂'), ('砂', '糖'), ('糖', '一'), ('一', '郎'), ('郎', '1'), ('1', '9')]

# 表記揺れ 解決方法まとめ

- 正規化
- n-gram 活用

> 複数の正規化処理をまとめたneologdnという便利なライブラリがある

> 土屋祐一郎. 15stepで踏襲 自然言語処理アプリケーション開発入門 (Japanese Edition) (Kindle の位置No.1065-1066). Kindle 版. 

> 表記のゆれを吸収し、ある一定の表記に統一する処理を行うことが一般的です。これを文字列の正規化（normalization）といいます。

> 土屋祐一郎. 15stepで踏襲 自然言語処理アプリケーション開発入門 (Japanese Edition) (Kindle の位置No.1057-1058). Kindle 版. 

In [31]:
import neologdn 

In [32]:
!pip show neologdn

Name: neologdn
Version: 0.4
Summary: Japanese text normalizer for mecab-neologd
Home-page: http://github.com/ikegami-yukino/neologdn
Author: Yukino Ikegami
Author-email: yknikgm@gmail.com
License: Apache Software License
Location: /opt/conda/lib/python3.7/site-packages
Requires: 
Required-by: 


In [33]:
text = '履歴書2019年12月25日現在ふりがなさとういちろう名前砂糖一郎1995年1月1日生（満24歳）男・女ふりがなとうきょうとちよだくさざんたわー電話000-0000-0000Emailtest1@sample.comふりがな電話Email年月学歴・職歴学歴20104東京都砂糖高等学校入学20133東京都砂糖高等学校卒業20134東京都菓子大学入学20173東京都菓子大学卒業職歴201710Donuts株式会社入社現在に至る以上現住所〒100-0000東京都千代田区サザンタワー現住所〒(現住所以外に連絡を希望する場合のみ入力)証明写真縦36mm〜40mm横24mm〜30mm本人単身胸から上裏面のりづけ年･2年･2年月学歴・職歴年月免許・資格201212TOEIC公開テスト800点取得志望動機・特技・アピールポイントなどDonutsは、サービスやゲームにおいて1年、2年で終わってしまうようなものではなく、世の中に何らかの価値をもたらし、100年先にもその価値が残り続けるものを目指してプロダクト創りをしています。そのために社会や時流に変化をもたらすもの創り出していこうという想いを込めてサービスを作り出しています。通勤時間電車約1時間00分扶養家族数（配偶者を除く）0人配偶者有・無配偶者の扶養義務有・無本人希望欄（特に給料・職種・勤務時間・勤務地・その他について希望があれば記入）Donutsは、サービスやゲームにおいて1年、2年で終わってしまうようなものではなく、世の中に何らかの価値をもたらし、100年先にもその価値が残り続けるものを目指してプロダクト創りをしています。そのために社会や時流に変化をもたらすもの創り出していこうという想いを込めてサービスを作り出しています。'

In [34]:
print(text)

履歴書2019年12月25日現在ふりがなさとういちろう名前砂糖一郎1995年1月1日生（満24歳）男・女ふりがなとうきょうとちよだくさざんたわー電話000-0000-0000Emailtest1@sample.comふりがな電話Email年月学歴・職歴学歴20104東京都砂糖高等学校入学20133東京都砂糖高等学校卒業20134東京都菓子大学入学20173東京都菓子大学卒業職歴201710Donuts株式会社入社現在に至る以上現住所〒100-0000東京都千代田区サザンタワー現住所〒(現住所以外に連絡を希望する場合のみ入力)証明写真縦36mm〜40mm横24mm〜30mm本人単身胸から上裏面のりづけ年･2年･2年月学歴・職歴年月免許・資格201212TOEIC公開テスト800点取得志望動機・特技・アピールポイントなどDonutsは、サービスやゲームにおいて1年、2年で終わってしまうようなものではなく、世の中に何らかの価値をもたらし、100年先にもその価値が残り続けるものを目指してプロダクト創りをしています。そのために社会や時流に変化をもたらすもの創り出していこうという想いを込めてサービスを作り出しています。通勤時間電車約1時間00分扶養家族数（配偶者を除く）0人配偶者有・無配偶者の扶養義務有・無本人希望欄（特に給料・職種・勤務時間・勤務地・その他について希望があれば記入）Donutsは、サービスやゲームにおいて1年、2年で終わってしまうようなものではなく、世の中に何らかの価値をもたらし、100年先にもその価値が残り続けるものを目指してプロダクト創りをしています。そのために社会や時流に変化をもたらすもの創り出していこうという想いを込めてサービスを作り出しています。


In [35]:
normalize_text = neologdn.normalize(text)

In [36]:
print(normalize_text.lower()) # 英字を小文字に変換

履歴書2019年12月25日現在ふりがなさとういちろう名前砂糖一郎1995年1月1日生(満24歳)男・女ふりがなとうきょうとちよだくさざんたわー電話000-0000-0000emailtest1@sample.comふりがな電話email年月学歴・職歴学歴20104東京都砂糖高等学校入学20133東京都砂糖高等学校卒業20134東京都菓子大学入学20173東京都菓子大学卒業職歴201710donuts株式会社入社現在に至る以上現住所〒100-0000東京都千代田区サザンタワー現住所〒(現住所以外に連絡を希望する場合のみ入力)証明写真縦36mm40mm横24mm30mm本人単身胸から上裏面のりづけ年・2年・2年月学歴・職歴年月免許・資格201212toeic公開テスト800点取得志望動機・特技・アピールポイントなどdonutsは、サービスやゲームにおいて1年、2年で終わってしまうようなものではなく、世の中に何らかの価値をもたらし、100年先にもその価値が残り続けるものを目指してプロダクト創りをしています。そのために社会や時流に変化をもたらすもの創り出していこうという想いを込めてサービスを作り出しています。通勤時間電車約1時間00分扶養家族数(配偶者を除く)0人配偶者有・無配偶者の扶養義務有・無本人希望欄(特に給料・職種・勤務時間・勤務地・その他について希望があれば記入)donutsは、サービスやゲームにおいて1年、2年で終わってしまうようなものではなく、世の中に何らかの価値をもたらし、100年先にもその価値が残り続けるものを目指してプロダクト創りをしています。そのために社会や時流に変化をもたらすもの創り出していこうという想いを込めてサービスを作り出しています。


# 訓練データの作成

ここはtrigramで生成してみる

In [37]:
import pandas as pd

In [336]:
name_list = ['明石海人', '秋山康之進', '青木恵哉', '暁烏敏', '明石海人', '麻生豊', '青柳文蔵']

In [337]:
name_list

['明石海人', '秋山康之進', '青木恵哉', '暁烏敏', '明石海人', '麻生豊', '青柳文蔵']

In [40]:
a = name_list[0]

In [41]:
a

'明石海人'

In [42]:
list(a)

['明', '石', '海', '人']

## n-gram & 訓練データの作成

In [361]:
def ngram(words, n):
    return list(zip(*(words[i:] for i in range(n))))

In [360]:
ngram(a, 2)

[('明', '石'), ('石', '海'), ('海', '人')]

一般的なノイズデータtextdata

In [372]:
t_p = []

for ii in range(len(name_list)):
    noize_text = 'ふりがなさとういちろう名前' + name_list[ii] + '1995年1月1日生(満24歳)男'
    t_p.append(noize_text)

print(t_p)


['ふりがなさとういちろう名前明石海人1995年1月1日生(満24歳)男', 'ふりがなさとういちろう名前秋山康之進1995年1月1日生(満24歳)男', 'ふりがなさとういちろう名前青木恵哉1995年1月1日生(満24歳)男', 'ふりがなさとういちろう名前暁烏敏1995年1月1日生(満24歳)男', 'ふりがなさとういちろう名前明石海人1995年1月1日生(満24歳)男', 'ふりがなさとういちろう名前麻生豊1995年1月1日生(満24歳)男', 'ふりがなさとういちろう名前青柳文蔵1995年1月1日生(満24歳)男']


In [390]:
def ngram(words, n):

    return list(zip(*(words[i:] for i in range(n))))

def con(num, text):
    s = '{},'.format(num)
    for i in text:
        s += i
    return s.split(',') 


cc = []
num_ngram = 15
for num in range(len(t_p)):
    text_parts = t_p[num]
    n = ngram(text_parts, num_ngram)
    c = [con(num, t) for t in ngram(text_parts, num_ngram)]
    cc.append(c)

In [391]:
import csv
with open("training_data.csv", "w", newline='') as f:
    w = csv.writer(f, delimiter=",")
    w.writerow(['label', 'text'])
    for c in cc:
        for  data_list in c:       
            w.writerow(data_list)
            

In [392]:
!cat training_data.csv

In [355]:
name_list

['明石海人', '秋山康之進', '青木恵哉', '暁烏敏', '明石海人', '麻生豊', '青柳文蔵']

## 回答データの作成

In [308]:
name_list = [[n] for n in name_list]

with open("replies.csv", "w", newline='') as f:
    w = csv.writer(f, delimiter=",")
    for  data_list in name_list:
        w.writerow(data_list)
        
        
!cat replies.csv       

## sklearn によるngram

In [218]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(analyzer = 'char', ngram_range=(3,3))
vectorizer.fit(t_p)
bow = vectorizer.transform(t_p)


In [219]:

print(bow.toarray())

[[1 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0]
 [1 1 0 0 0 1 0 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0]
 [1 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0]
 [1 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [1 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 1]
 [1 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0]]


In [220]:
vectorizer.vocabulary_

{'う名前': 0,
 '名前明': 9,
 '前明石': 3,
 '明石海': 20,
 '石海人': 27,
 '海人1': 24,
 '人19': 2,
 '名前秋': 11,
 '前秋山': 5,
 '秋山康': 28,
 '山康之': 15,
 '康之進': 16,
 '之進1': 1,
 '進19': 31,
 '名前青': 12,
 '前青木': 6,
 '青木恵': 32,
 '木恵哉': 22,
 '恵哉1': 17,
 '哉19': 14,
 '名前暁': 10,
 '前暁烏': 4,
 '暁烏敏': 21,
 '烏敏1': 25,
 '敏19': 18,
 '名前麻': 13,
 '前麻生': 8,
 '麻生豊': 34,
 '生豊1': 26,
 '豊19': 30,
 '前青柳': 7,
 '青柳文': 33,
 '柳文蔵': 23,
 '文蔵1': 19,
 '蔵19': 29}

# 名字と名前のベクトル化：BoW（Bag of words）



In [25]:
import MeCab
tagger = MeCab.Tagger()


In [26]:
def tokenize(text):
    node = tagger.parseToNode(text)
    tokens = []
    while node:
        if node.surface != '':
            tokens.append(node.surface)
        node = node.next
    return tokens

In [27]:
texts = [
    '私は私のことが好きなあなたが好きです',
    '私はラーメンが好きです',
    '富士山は日本一高い山です',
]

In [45]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(tokenizer = tokenize)
vectorizer.fit(name_list)
bow = vectorizer.transform(name_list)

/opt/conda/lib/python3.7/site-packages/sklearn/feature_extraction/text.py:507: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn("The parameter 'token_pattern' will not be used"


In [46]:
import pandas as pd
bow_table = pd.DataFrame(bow.toarray(), columns=vectorizer.get_feature_names())
print('Shape: {}'.format(bow.shape))
bow_table

Shape: (7, 13)


哉  康之  恵  文蔵  明石  暁烏敏  海人  秋山  豊  進  青木  青柳  麻生
0  0   0  0   0   1    0   1   0  0  0   0   0   0
1  0   1  0   0   0    0   0   1  0  1   0   0   0
2  1   0  1   0   0    0   0   0  0  0   1   0   0
3  0   0  0   0   0    1   0   0  0  0   0   0   0
4  0   0  0   0   1    0   1   0  0  0   0   0   0
5  0   0  0   0   0    0   0   0  1  0   0   0   1
6  0   0  0   1   0    0   0   0  0  0   0   1   0

# PyTorch

In [50]:
!pip install torch

     |████████████████████████████████| 753.4 MB 5.9 MB/s eta 0:00:012   |▋                               | 13.9 MB 3.7 MB/s eta 0:03:20     |█▉                              | 41.9 MB 8.2 MB/s eta 0:01:27     |███▎                            | 75.9 MB 3.9 MB/s eta 0:02:56     |███▋                            | 84.4 MB 5.7 MB/s eta 0:01:58     |████                            | 92.1 MB 4.9 MB/s eta 0:02:16     |████▏                           | 99.1 MB 7.1 MB/s eta 0:01:32     |█████                           | 115.5 MB 5.9 MB/s eta 0:01:48     |█████▏                          | 120.6 MB 6.1 MB/s eta 0:01:44     |█████▋                          | 132.9 MB 9.9 MB/s eta 0:01:03     |█████▊                          | 133.9 MB 9.9 MB/s eta 0:01:03     |██████▋                         | 156.1 MB 4.1 MB/s eta 0:02:27     |██████▉                         | 161.5 MB 5.7 MB/s eta 0:01:45     |██████▉                         | 162.0 MB 5.7 MB/s eta 0:01:45     |████████                        | 1

In [51]:
import torch
import torch.autograd as autograd
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)


In [52]:
# torch.tensor(data) creates a torch.Tensor object with the given data.
V_data = [1., 2., 3.]
V = torch.tensor(V_data)
print(V)

tensor([1., 2., 3.])


In [53]:
# Creates a matrix
M_data = [[1., 2., 3.], [4., 5., 6]]
M = torch.tensor(M_data)
print(M)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [54]:
# Create a 3D tensor of size 2x2x2.
T_data = [[[1., 2.], [3., 4.]],
          [[5., 6.], [7., 8.]]]
T = torch.tensor(T_data)
print(T)

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])


In [55]:
x = torch.randn((3, 4, 5))
print(x)


tensor([[[-1.5256, -0.7502, -0.6540, -1.6095, -0.1002],
         [-0.6092, -0.9798, -1.6091, -0.7121,  0.3037],
         [-0.7773, -0.2515, -0.2223,  1.6871,  0.2284],
         [ 0.4676, -0.6970, -1.1608,  0.6995,  0.1991]],

        [[ 0.8657,  0.2444, -0.6629,  0.8073,  1.1017],
         [-0.1759, -2.2456, -1.4465,  0.0612, -0.6177],
         [-0.7981, -0.1316,  1.8793, -0.0721,  0.1578],
         [-0.7735,  0.1991,  0.0457,  0.1530, -0.4757]],

        [[-0.1110,  0.2927, -0.1578, -0.0288,  0.4533],
         [ 1.1422,  0.2486, -1.7754, -0.0255, -1.0233],
         [-0.5962, -1.0055,  0.4285,  1.4761, -1.7869],
         [ 1.6103, -0.7040, -0.1853, -0.9962, -0.8313]]])


## DEEP LEARNING WITH PYTORCH

https://pytorch.org/tutorials/beginner/deep_learning_nlp_tutorial.html

In [56]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

In [59]:
data = torch.randn(5)
data

tensor([0.2879, 1.0579, 0.9621, 0.3935, 1.1322])

In [62]:
print(data)
print(F.softmax(data, dim=0))
print(F.softmax(data, dim=0).sum())
print(F.log_softmax(data, dim=0))

tensor([0.2879, 1.0579, 0.9621, 0.3935, 1.1322])
tensor([0.1168, 0.2523, 0.2293, 0.1298, 0.2718])
tensor(1.)
tensor([-2.1471, -1.3771, -1.4729, -2.0415, -1.3028])


In [63]:
data = [("me gusta comer en la cafeteria".split(), "SPANISH"),
        ("Give it to me".split(), "ENGLISH"),
        ("No creo que sea una buena idea".split(), "SPANISH"),
        ("No it is not a good idea to get lost at sea".split(), "ENGLISH")]

test_data = [("Yo creo que si".split(), "SPANISH"),
             ("it is lost on me".split(), "ENGLISH")]

Make BoW

In [65]:
word_to_ix = {}

for sent, _ in data + test_data:
    for word in sent:
        if word not in word_to_ix:
            word_to_ix[word] = len(word_to_ix)
print(word_to_ix)            

{'me': 0, 'gusta': 1, 'comer': 2, 'en': 3, 'la': 4, 'cafeteria': 5, 'Give': 6, 'it': 7, 'to': 8, 'No': 9, 'creo': 10, 'que': 11, 'sea': 12, 'una': 13, 'buena': 14, 'idea': 15, 'is': 16, 'not': 17, 'a': 18, 'good': 19, 'get': 20, 'lost': 21, 'at': 22, 'Yo': 23, 'si': 24, 'on': 25}


In [66]:
VOCAB_SIZE = len(word_to_ix)
NUM_LABELS = 2


In [69]:
class BoWClassifier(nn.Module):  # inheriting from nn.Module!

    def __init__(self, num_labels, vocab_size):
        # calls the init function of nn.Module.  Dont get confused by syntax,
        # just always do it in an nn.Module
        super(BoWClassifier, self).__init__()

        # Define the parameters that you will need.  In this case, we need A and b,
        # the parameters of the affine mapping.
        # Torch defines nn.Linear(), which provides the affine map.
        # Make sure you understand why the input dimension is vocab_size
        # and the output is num_labels!
        self.linear = nn.Linear(vocab_size, num_labels)

        # NOTE! The non-linearity log softmax does not have parameters! So we don't need
        # to worry about that here

    def forward(self, bow_vec):
        # Pass the input through the linear layer,
        # then pass that through log_softmax.
        # Many non-linearities and other functions are in torch.nn.functional
        return F.log_softmax(self.linear(bow_vec), dim=1)
    
def make_bow_vector(sentence, word_to_ix):
    vec = torch.zeros(len(word_to_ix))
    for word in sentence:
        vec[word_to_ix[word]] += 1
    return vec.view(1, -1)

def make_target(label, label_to_ix):
    return torch.LongTensor([label_to_ix[label]])



In [70]:
model = BoWClassifier(NUM_LABELS, VOCAB_SIZE)

for param in model.parameters():
    print(param)

Parameter containing:
tensor([[ 0.0394,  0.0471, -0.1313, -0.0931,  0.0669,  0.0351, -0.0834, -0.0594,
          0.1796, -0.0363,  0.1106,  0.0849, -0.1268, -0.1668,  0.1882,  0.0102,
          0.1344,  0.0406,  0.0631,  0.1465,  0.1860, -0.1301,  0.0245,  0.1464,
          0.1421,  0.1218],
        [-0.1419, -0.1412, -0.1186,  0.0246,  0.1955, -0.1239,  0.1045, -0.1085,
         -0.1844, -0.0417,  0.1130,  0.1821, -0.1218,  0.0426,  0.1692,  0.1300,
          0.1222,  0.1394,  0.1240,  0.0507, -0.1341, -0.1647, -0.0899, -0.0228,
         -0.1202,  0.0717]], requires_grad=True)
Parameter containing:
tensor([ 0.0607, -0.0444], requires_grad=True)


In [75]:
with torch.no_grad():
    sample = data[0]
    print(sample)
    bow_vector = make_bow_vector(sample[0], word_to_ix)
    print(bow_vector)
    log_probs = model(bow_vector)
    print(log_probs)

(['me', 'gusta', 'comer', 'en', 'la', 'cafeteria'], 'SPANISH')
tensor([[1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0.]])
tensor([[-0.0103, -4.5792]])


In [72]:
label_to_ix = {"SPANISH": 0, "ENGLISH": 1}


では、訓練しましょう。これを行うには、インスタンスを渡して対数確率を取得し、損失関数を計算し、損失関数の勾配を計算し、勾配ステップでパラメータを更新します。損失関数は Torch が nn パッケージで提供しています。 nn.NLLLoss() は、我々が求める負の対数尤度損失です。また、最適化関数も torch.optim で定義されています。ここではSGDを使用します。

NLLLossへの入力は対数確率のベクトルとターゲットラベルであることに注意してください。NLLLoss は対数確率を計算してくれません。これが、ネットワークの最後の層が log softmax である理由です。損失関数 nn.CrossEntropyLoss() は NLLLoss() と同じですが、log softmax を計算してくれる点を除けば、NLLLoss() と同じです。

In [78]:
# Run on test data before we train, just to see a before-and-after
with torch.no_grad():
    for instance, label in test_data:
        bow_vec = make_bow_vector(instance, word_to_ix)
        log_probs = model(bow_vec)
        print(log_probs)

# Print the matrix column corresponding to "creo"
print(next(model.parameters())[:, word_to_ix["creo"]])

loss_function = nn.NLLLoss()
optimizer = optim.SGD(model.parameters(), lr=0.1)

tensor([[-0.0654, -2.7602]])
tensor([[-3.0735, -0.0474]])
tensor([ 0.6468, -0.4232], grad_fn=<SelectBackward>)


In [79]:


# 通常、学習データを何度か通過させたいと思うでしょう。100は実際のデータセットよりもはるかに大きいですが、実際のデータセットでは2つのインスタンスを使用します。 通常、5～30エポックの間のどこかが妥当です。
# Usually you want to pass over the training data several times.
# 100 is much bigger than on a real data set, but real datasets have more than
# two instances.  Usually, somewhere between 5 and 30 epochs is reasonable.
for epoch in range(100):
    for instance, label in data:
        # Step 1. Remember that PyTorch accumulates gradients.
        # We need to clear them out before each instance
        model.zero_grad()

        # Step 2. Make our BOW vector and also we must wrap the target in a
        # Tensor as an integer. For example, if the target is SPANISH, then
        # we wrap the integer 0. The loss function then knows that the 0th
        # element of the log probabilities is the log probability
        # corresponding to SPANISH
        bow_vec = make_bow_vector(instance, word_to_ix)
        target = make_target(label, label_to_ix)

        # Step 3. Run our forward pass.
        log_probs = model(bow_vec)

        # Step 4. Compute the loss, gradients, and update the parameters by
        # calling optimizer.step()
        loss = loss_function(log_probs, target)
        loss.backward()
        optimizer.step()

with torch.no_grad():
    for instance, label in test_data:
        bow_vec = make_bow_vector(instance, word_to_ix)
        log_probs = model(bow_vec)
        print(log_probs)

# Index corresponding to Spanish goes up, English goes down!
print(next(model.parameters())[:, word_to_ix["creo"]])

tensor([[-0.0562, -2.9067]])
tensor([[-3.2892, -0.0380]])
tensor([ 0.6826, -0.4590], grad_fn=<SelectBackward>)


In [103]:
with torch.enable_grad():
    
    for instance, label in test_data:
        bow_vec = make_bow_vector(instance, word_to_ix)
        log_probs = model(bow_vec)
        print(log_probs)

# Index corresponding to Spanish goes up, English goes down!
print(next(model.parameters())[:, word_to_ix["creo"]])

tensor([[-0.0562, -2.9067]], grad_fn=<LogSoftmaxBackward>)
tensor([[-3.2892, -0.0380]], grad_fn=<LogSoftmaxBackward>)
tensor([ 0.6826, -0.4590], grad_fn=<SelectBackward>)


In [80]:
import torch

# Creating the graph
x = torch.tensor(1.0, requires_grad = True)
y = torch.tensor(2.0)
z = x * y

# Displaying
for i, name in zip([x, y, z], "xyz"):
    print(f"{name}\ndata: {i.data}\nrequires_grad: {i.requires_grad}\n\
grad: {i.grad}\ngrad_fn: {i.grad_fn}\nis_leaf: {i.is_leaf}\n")

x
data: 1.0
requires_grad: True
grad: None
grad_fn: None
is_leaf: True

y
data: 2.0
requires_grad: False
grad: None
grad_fn: None
is_leaf: True

z
data: 2.0
requires_grad: True
grad: None
grad_fn: <MulBackward0 object at 0x7fea7cffc410>
is_leaf: False



# NLP_studyのやつパクリ

In [576]:
from os.path import dirname, join, normpath

import MeCab
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.pipeline import Pipeline
from sklearn.svm import SVC


class DialogueAgent:
    def __init__(self):
        self.tagger = MeCab.Tagger()

    def _tokenize(self, text): # 形態素解析
        node = self.tagger.parseToNode(text)

        tokens = []
        while node:
            if node.surface != '':
                tokens.append(node.surface)
 
            node = node.next
        return tokens

    def train(self, texts, labels): # 2. 文章とラベルからニューラルネットワークを更新
        pipeline = Pipeline([
            ('vecttorizer', CountVectorizer(tokenizer=self._tokenize)), 
            ('classifier', SVC()),
        ])
        pipeline.fit(texts, labels)
        self.pipeline = pipeline

    def predict(self, texts): # 3. 他の文章でのニューロンの反応をチェック
        return self.pipeline.predict(texts)


if __name__ == '__main__':
    BASE_DIR = normpath(dirname('__file__'))

    training_data = pd.read_csv(join(BASE_DIR, './training_data.csv'))  # 学習用読み込み文章

    dialogue_agent = DialogueAgent()
    dialogue_agent.train(training_data['text'], training_data['label']) # 学習用読み込み文章とラベルの組を学習

    with open(join(BASE_DIR, './replies.csv')) as f:  # 応答文章
        replies = f.read().split('\n')

    input_text = '名前を教えてよ'
    predictions = dialogue_agent.predict([input_text]) 
    predicted_class_id = predictions[0]  

    print(replies[predicted_class_id])

    while True:
        input_text = input()
        predictions = dialogue_agent.predict([input_text])
        predicted_class_id = predictions[0]

        print('AI reply: ' + replies[predicted_class_id])
        print()

暁烏敏
りがなさとういちろう名前青柳文蔵1995
AI reply: 青柳文蔵



KeyboardInterrupt: 

# 自作検索関数

In [415]:
t.find('固有名詞', 0, 100)    



-1

In [420]:

# reモジュールをインポート
import re

# 'two'にマッチした結果をマッチオブジェクトで返す
re.search(r'two', s).span()



(4, 7)

In [418]:

# span()メソッドを使うと、位置が返ります。
re.search(r'\w{3}', s).span()


(0, 3)

In [423]:

test_L = [500,0,0,0,0,0,0,500,200]
index_num = [n for n, v in enumerate(test_L) if v == 500]
print(index_num)

[0, 7]


In [424]:
s.find('two')

4

In [442]:
s.find('two', 5)


'two' in s

True

In [567]:
def pull_out(text, word, buffer):
    num = 0
    for i in range(len(text)):
        evalu = word in text[num:]
        if  evalu == True:
            num = text.find(word, num+1)
            print(text[num-buffer:num+buffer])                      

In [515]:
mytext = '履歴書2019年12月25日現在ふりがなさとういちろう名前青柳文蔵1995年1月1日生(満24歳)男・女ふりがなとうきょうとちよだくさざんたわー電話000-0000-0000emailtest1@sample.comふりがな電話email年月学歴・職歴学歴20104東京都砂糖高等学校入学20133東京都砂糖高等学校卒業20134東京都菓子大学入学20173東京都菓子大学卒業職歴201710donuts株式会社入社現在に至る以上現住所〒100-0000東京都千代田区サザンタワー現住所〒(現住所以外に連絡を希望する場合のみ入力)証明写真縦36mm40mm横24mm30mm本人単身胸から上裏面のりづけ年・2年・2年月学歴・職歴年月免許・資格201212toeic公開テスト800点取得志望動機・特技・アピールポイントなどdonutsは、サービスやゲームにおいて1年、2年で終わってしまうようなものではなく、世の中に何らかの価値をもたらし、100年先にもその価値が残り続けるものを目指してプロダクト創りをしています。そのために社会や時流に変化をもたらすもの創り出していこうという想いを込めてサービスを作り出しています。通勤時間電車約1時間00分扶養家族数(配偶者を除く)0人配偶者有・無配偶者の扶養義務有・無本人希望欄(特に給料・職種・勤務時間・勤務地・その他について希望があれば記入)donutsは、サービスやゲームにおいて1年、2年で終わってしまうようなものではなく、世の中に何らかの価値をもたらし、100年先にもその価値が残り続けるものを目指してプロダクト創りをしています。そのために社会や時流に変化をもたらすもの創り出していこうという想いを込めてサービスを作り出しています。 '


In [516]:
import MeCab
tagger = MeCab.Tagger()
print(tagger.parse(mytext))
t = tagger.parse(mytext)

履歴	名詞,一般,*,*,*,*,履歴,リレキ,リレキ
書	名詞,接尾,一般,*,*,*,書,ショ,ショ
2019	名詞,数,*,*,*,*,*
年	名詞,接尾,助数詞,*,*,*,年,ネン,ネン
12	名詞,数,*,*,*,*,*
月	名詞,一般,*,*,*,*,月,ツキ,ツキ
25	名詞,数,*,*,*,*,*
日	名詞,接尾,助数詞,*,*,*,日,ニチ,ニチ
現在	名詞,副詞可能,*,*,*,*,現在,ゲンザイ,ゲンザイ
ふりがな	名詞,一般,*,*,*,*,ふりがな,フリガナ,フリガナ
さとう	形容詞,自立,*,*,形容詞・アウオ段,連用ゴザイ接続,さとい,サトウ,サトー
いちろう	名詞,固有名詞,人名,名,*,*,いちろう,イチロウ,イチロー
名前	名詞,一般,*,*,*,*,名前,ナマエ,ナマエ
青柳	名詞,一般,*,*,*,*,青柳,アオヤギ,アオヤギ
文蔵	名詞,固有名詞,地域,一般,*,*,文蔵,ブゾウ,ブゾー
1995	名詞,数,*,*,*,*,*
年	名詞,接尾,助数詞,*,*,*,年,ネン,ネン
1	名詞,数,*,*,*,*,*
月	名詞,一般,*,*,*,*,月,ツキ,ツキ
1	名詞,数,*,*,*,*,*
日生	名詞,固有名詞,組織,*,*,*,日生,ニッセイ,ニッセイ
(	名詞,サ変接続,*,*,*,*,*
満	接頭詞,数接続,*,*,*,*,満,マン,マン
24	名詞,数,*,*,*,*,*
歳	名詞,接尾,助数詞,*,*,*,歳,サイ,サイ
)	名詞,サ変接続,*,*,*,*,*
男	名詞,一般,*,*,*,*,男,オトコ,オトコ
・	記号,一般,*,*,*,*,・,・,・
女	名詞,一般,*,*,*,*,女,オンナ,オンナ
ふりがな	名詞,一般,*,*,*,*,ふりがな,フリガナ,フリガナ
とうき	名詞,一般,*,*,*,*,とうき,トウキ,トーキ
ょうとちよだくさざんたわ	名詞,一般,*,*,*,*,*
ー	名詞,一般,*,*,*,*,*
電話	名詞,サ変接続,*,*,*,*,電話,デンワ,デンワ
000	名詞,数,*,*,*,*,*
-	名詞,サ変接続,*,*,*,*,*
0000	名詞,数,*,*,*,*,*
-	名詞,サ変接続,*,*,*,*,*
0000	名詞,数,*,*,*,*,*
emailtest	名詞,一般,*

In [564]:
s = 'one-two-three-two-one'

pull_out(s,'two', 5)

two-t
two-o



In [575]:
mytext = '履歴書2019年12月25日現在ふりがなさとういちろう名前青柳文蔵1995年1月1日生(満24歳)男・女ふりがなとうきょうとちよだくさざんたわー電話000-0000-0000emailtest1@sample.comふりがな電話email年月学歴・職歴学歴20104東京都砂糖高等学校入学20133東京都砂糖高等学校卒業20134東京都菓子大学入学20173東京都菓子大学卒業職歴201710donuts株式会社入社現在に至る以上現住所〒100-0000東京都千代田区サザンタワー現住所〒(現住所以外に連絡を希望する場合のみ入力)証明写真縦36mm40mm横24mm30mm本人単身胸から上裏面のりづけ年・2年・2年月学歴・職歴年月免許・資格201212toeic公開テスト800点取得志望動機・特技・アピールポイントなどdonutsは、サービスやゲームにおいて1年、2年で終わってしまうようなものではなく、世の中に何らかの価値をもたらし、100年先にもその価値が残り続けるものを目指してプロダクト創りをしています。そのために社会や時流に変化をもたらすもの創り出していこうという想いを込めてサービスを作り出しています。通勤時間電車約1時間00分扶養家族数(配偶者を除く)0人配偶者有・無配偶者の扶養義務有・無本人希望欄(特に給料・職種・勤務時間・勤務地・その他について希望があれば記入)donutsは、サービスやゲームにおいて1年、2年で終わってしまうようなものではなく、世の中に何らかの価値をもたらし、100年先にもその価値が残り続けるものを目指してプロダクト創りをしています。そのために社会や時流に変化をもたらすもの創り出していこうという想いを込めてサービスを作り出しています。'

pull_out(mytext, '名前', 10)

りがなさとういちろう名前青柳文蔵1995



In [571]:
pull_out(t, '人名', 50)

,自立,*,*,形容詞・アウオ段,連用ゴザイ接続,さとい,サトウ,サトー
いちろう	名詞,固有名詞,人名,名,*,*,いちろう,イチロウ,イチロー
名前	名詞,一般,*,*,*,*,名前,ナマエ,ナマ
*,配偶,ハイグウ,ハイグー
者	名詞,接尾,一般,*,*,*,者,シャ,シャ
有	名詞,固有名詞,人名,名,*,*,有,ユウ,ユー
・	記号,一般,*,*,*,*,・,・,・
無	接頭詞,名詞接続,
,*,扶養,フヨウ,フヨー
義務	名詞,一般,*,*,*,*,義務,ギム,ギム
有	名詞,固有名詞,人名,名,*,*,有,ユウ,ユー
・	記号,一般,*,*,*,*,・,・,・
無	接頭詞,名詞接続,



In [509]:
t = '履歴書2019年12月25日現在ふりがなさとういちろ'
def pull_out(text, word):
    num = 0
    for i in range(50):
        evalu = 'two' in text[num:]
        print(text[num:])
        print(evalu)
        if  evalu == True:
            num = text.find(word, num+1)
            print(s[num:num+5])

pull_out(t, '年')

履歴書2019年12月25日現在ふりがなさとういちろ
False
履歴書2019年12月25日現在ふりがなさとういちろ
False
履歴書2019年12月25日現在ふりがなさとういちろ
False
履歴書2019年12月25日現在ふりがなさとういちろ
False
履歴書2019年12月25日現在ふりがなさとういちろ
False
履歴書2019年12月25日現在ふりがなさとういちろ
False
履歴書2019年12月25日現在ふりがなさとういちろ
False
履歴書2019年12月25日現在ふりがなさとういちろ
False
履歴書2019年12月25日現在ふりがなさとういちろ
False
履歴書2019年12月25日現在ふりがなさとういちろ
False
履歴書2019年12月25日現在ふりがなさとういちろ
False
履歴書2019年12月25日現在ふりがなさとういちろ
False
履歴書2019年12月25日現在ふりがなさとういちろ
False
履歴書2019年12月25日現在ふりがなさとういちろ
False
履歴書2019年12月25日現在ふりがなさとういちろ
False
履歴書2019年12月25日現在ふりがなさとういちろ
False
履歴書2019年12月25日現在ふりがなさとういちろ
False
履歴書2019年12月25日現在ふりがなさとういちろ
False
履歴書2019年12月25日現在ふりがなさとういちろ
False
履歴書2019年12月25日現在ふりがなさとういちろ
False
履歴書2019年12月25日現在ふりがなさとういちろ
False
履歴書2019年12月25日現在ふりがなさとういちろ
False
履歴書2019年12月25日現在ふりがなさとういちろ
False
履歴書2019年12月25日現在ふりがなさとういちろ
False
履歴書2019年12月25日現在ふりがなさとういちろ
False
履歴書2019年12月25日現在ふりがなさとういちろ
False
履歴書2019年12月25日現在ふりがなさとういちろ
False
履歴書2019年12月25日現在ふりがなさとういちろ
False
履歴書2019年12月25日現在ふりがなさとういちろ
False
履歴書2019年12月25日現在ふりがなさとういちろ
False
履歴書2019年12

In [504]:
t = '履歴書2019年12月25日現在ふりがなさとういちろ'

word = '9'
def pull_out(text, word):
    num = 0
    for i in range(len(t)):
        print(num)       
        evalu = word in text[num:]
        print(text[num:])
        print(evalu)
        if  evalu == True:
            num = text.find(word, num+1)
            print(s[num:num+5])
            
pull_out(t, word)            

0
履歴書2019年12月25日現在ふりがなさとういちろ
True
o-thr
6
9年12月25日現在ふりがなさとういちろ
True

-1
ろ
False
-1
ろ
False
-1
ろ
False
-1
ろ
False
-1
ろ
False
-1
ろ
False
-1
ろ
False
-1
ろ
False
-1
ろ
False
-1
ろ
False
-1
ろ
False
-1
ろ
False
-1
ろ
False
-1
ろ
False
-1
ろ
False
-1
ろ
False
-1
ろ
False
-1
ろ
False
-1
ろ
False
-1
ろ
False
-1
ろ
False
-1
ろ
False
-1
ろ
False
-1
ろ
False


# 名字検索AI作成

In [586]:
#対象の文字列
src = "aaabbbccc"
 
# すべて置換
dst = src.replace("b", "B")
 
print(src, "->", dst)    # aaabbbccc -> aaaBBBccc

aaabbbccc -> aaaBBBccc


In [601]:
text = 'こんにちは。\r\nありがとう！'
print(text)


text = text.replace('\r\n','')
print(text)


こんにちは。
ありがとう！
こんにちは。ありがとう！


In [604]:
with open('./name1') as f:
    read_data = list(f)
    print(f)
    
print(read_data[0])
print(read_data[0].replace('\n', ''))
    
    
name_list = [r.replace("\n", "") for r in read_data ]


<_io.TextIOWrapper name='./name1' mode='r' encoding='UTF-8'>
佐藤

佐藤


In [605]:
def ngram(words, n):
    return list(zip(*(words[i:] for i in range(n))))

In [607]:
t_p = []

for ii in range(len(name_list)):
    noize_text = '名前' + name_list[ii] + '199'
    t_p.append(noize_text)

print(t_p)


['名前佐藤199', '名前鈴木199', '名前高橋199', '名前田中199', '名前伊藤199', '名前山本199', '名前渡辺199', '名前中村199', '名前小林199', '名前加藤199', '名前吉田199', '名前山田199', '名前木199', '名前山口199', '名前松本199', '名前井上199', '名前木村199', '名前林199', '名前斎藤199', '名前清水199', '名前山崎199', '名前阿部199', '名前森199', '名前池田199', '名前橋本199', '名前山下199', '名前石川199', '名前中島199', '名前前田199', '名前藤田199', '名前後藤199', '名前小川199', '名前岡田199', '名前村上199', '名前長谷川199', '名前近藤199', '名前石井199', '名前斉藤199', '名前坂本199', '名前遠藤199', '名前藤井199', '名前青木199', '名前福田199', '名前三浦199', '名前西村199', '名前藤原199', '名前太田199', '名前松田199', '名前原田199', '名前岡本199', '名前中野199', '名前中川199', '名前小野199', '名前田村199', '名前竹内199', '名前金子199', '名前中山199', '名前和田199', '名前石田199', '名前工藤199', '名前上田199', '名前原199', '名前森田199', '名前酒井199', '名前横山199', '名前柴田199', '名前宮崎199', '名前宮本199', '名前内田199', '名前高木199', '名前谷口199', '名前安藤199', '名前丸山199', '名前今井199', '名前大野199', '名前高田199', '名前菅原199', '名前河野199', '名前武田199', '名前藤本199', '名前上野199', '名前杉山199', '名前千葉199', '名前村田199', '名前増田199', '名前小島199', '名前小山199', '名前大塚199', '名前平野199', '名前久保199', '名前渡部199', '

In [609]:
def ngram(words, n):

    return list(zip(*(words[i:] for i in range(n))))

def con(num, text):
    s = '{},'.format(num)
    for i in text:
        s += i
    return s.split(',') 


cc = []
num_ngram = 3
for num in range(len(t_p)):
    text_parts = t_p[num]
    n = ngram(text_parts, num_ngram)
    c = [con(num, t) for t in ngram(text_parts, num_ngram)]
    cc.append(c)
    
import csv
with open("training_data.csv", "w", newline='') as f:
    w = csv.writer(f, delimiter=",")
    w.writerow(['label', 'text'])
    for c in cc:
        for  data_list in c:       
            w.writerow(data_list)

            
!cat training_data.csv            

In [610]:
# 回答データの作成

name_list = [[n] for n in name_list]

with open("replies.csv", "w", newline='') as f:
    w = csv.writer(f, delimiter=",")
    for  data_list in name_list:
        w.writerow(data_list)
        
        
!cat replies.csv       

In [ ]:
from os.path import dirname, join, normpath

import MeCab
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.pipeline import Pipeline
from sklearn.svm import SVC


class DialogueAgent:
    def __init__(self):
        self.tagger = MeCab.Tagger()

    def _tokenize(self, text): # 形態素解析
        node = self.tagger.parseToNode(text)

        tokens = []
        while node:
            if node.surface != '':
                tokens.append(node.surface)
 
            node = node.next
        return tokens

    def train(self, texts, labels): # 2. 文章とラベルからニューラルネットワークを更新
        pipeline = Pipeline([
            ('vecttorizer', CountVectorizer(tokenizer=self._tokenize)), 
            ('classifier', SVC()),
        ])
        pipeline.fit(texts, labels)
        self.pipeline = pipeline

    def predict(self, texts): # 3. 他の文章でのニューロンの反応をチェック
        return self.pipeline.predict(texts)


if __name__ == '__main__':
    BASE_DIR = normpath(dirname('__file__'))

    training_data = pd.read_csv(join(BASE_DIR, './training_data.csv'))  # 学習用読み込み文章

    dialogue_agent = DialogueAgent()
    dialogue_agent.train(training_data['text'], training_data['label']) # 学習用読み込み文章とラベルの組を学習

    with open(join(BASE_DIR, './replies.csv')) as f:  # 応答文章
        replies = f.read().split('\n')

    input_text = '長a谷w川'
    predictions = dialogue_agent.predict([input_text]) 
    predicted_class_id = predictions[0]  

    print(replies[predicted_class_id])

    while True:
        input_text = input()
        predictions = dialogue_agent.predict([input_text])
        predicted_class_id = predictions[0]

        print('AI reply: ' + replies[predicted_class_id])
        print()

長谷川
佐藤健太
AI reply: 佐藤

健太佐藤
AI reply: 佐藤

斎藤健太
AI reply: 斎藤

satou
AI reply: 長谷川

